### ISSUE TITLE
Avaliacao

### ISSUE THREAD

**Issue by thiagopaschoal** [BrOrlandi/GitTrainingWall#79]
Olá Bruno, tudo bem?

Cara, eu desenvolvi um README.md com alguns comandos do Git.

Poderia avaliar? Ver se está legal

Obrigado

https://github.com/thiagopaschoal/exercicios-git

**Comment by BrOrlandi** [comment]
Legal Thiago!

Ficou muito bom!

Algumas sugestões de melhoria:

**git pull**: lembrar que ele faz o merge das alterações 

**git checkout**: seria legal adicionar esse comando também, indicando q ele é util para mudar de branch.
No seu arquivo vc só citou o `git checkout -b`.

**git blame**: ele é bem diferente do `git log`, neste caso vc usa em um arquivo e consegue ver detalhes em qual commit foi feito cada linha do arquivo.

Assim que verificar aqui, pode fechar a issue. 😉

**Comment by thiagopaschoal** [comment]
Obrigado Bruno, vou alterar aqui

**Comment by thiagopaschoal** [comment]
Corrigido
